//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBook
    {
        public int ID { get; set; }
        public decimal Price { get; set; }
        public decimal SalePrice { get; set; }
        public int BookID { get; set; }
        public int OrderID { get; set; }
        public int Amount { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
